---
version: "3"

services:
  runtime:
    image: sitepilot/runtime:${RUNTIME_VERSION:-1.0}
    environment:
      RUNTIME_USER_ID: "${RUNTIME_USER_ID:-10000}"
      RUNTIME_GROUP_ID: "${RUNTIME_GROUP_ID:-10000}"
    ports:
      - "${RUNTIME_HTTP_PORT:-8080}:80"
      - "${RUNTIME_HTTPS_PORT:-8443}:443"
    volumes:
      - ".:/opt/runtime/app/public"
    networks:
      - flight
 
networks:
  flight:
    driver: bridge
