---
version: "3"

services:
  runtime:
    build:
      context: ./runtimes/1.0
      dockerfile: Dockerfile
    image: ghcr.io/sitepilot/runtime:1.0
    environment:
      RUNTIME_USER_ID: "${FLIGHT_USER_ID:-10000}"
    networks:
      - flight

networks:
  flight:
    external: true
